### ISSUE TITLE
why i get this?

### ISSUE THREAD

**Issue by Chawki726** [amandeepmittal/rn-todos-example#1]
` saveItems = newItem=> {
    const saveItem = AsyncStorage.setItem("Todos", JSON.stringify(newItem));
  };`

###  i get this  error  👇

> 'saveItems' is assigned a value but never used

**Comment by amandeepmittal** [comment]
This seems a linting error. Please check your eslint config or the compiler. Also, in `Main.js` what are you using to save each individual todo item?
